global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 15s
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "current-server"
    static_configs:
      - targets: ["node_exporter:9100"]

  - job_name: "cadvisor"
    scrape_interval: 5s
    static_configs:
      - targets: ["192.168.1.26:8080"]

